/* eslint-disable func-style */
/* eslint-disable max-len */
/* eslint-disable require-jsdoc */
function addMsg (Blockly) {
    Object.assign(Blockly.ScratchMsgs.locales.en, {
        IRON_KIT_CATEGORY: 'Pico Lab Sensors',
        PICOLABSENSORS_INIT: 'pico lab sensors kit',
        PICOLABSENSORS_SETSERVODEGREE: 'set servo %1 degree %2',
        PICOLABSENSORS_SETMOTORSPEED: 'set motor %1 direction %2 speed %3',
        PICOLABSENSORS_FORWARD: 'forward',
        PICOLABSENSORS_BACKWARD: 'backward',
        PICOLABSENSORS_STOPMOTOR: 'break motor %1',
        PICOLABSENSORS_SETRGBLEDCOLOR: '设置RGB LED %1 颜色为 %2',
        PICOLABSENSORS_ALL: 'all',
        PICOLABSENSORS_LEFT: 'left',
        PICOLABSENSORS_RIGHT: 'right',
        PICOLABSENSORS_SETBUZZER: 'Buzzer play %1',
        PICOLABSENSORS_SOUND_CONNECT: 'connect',
        PICOLABSENSORS_SOUND_DISCONNECT: 'disconnect',
        PICOLABSENSORS_SOUND_BUTTON: 'button',
        PICOLABSENSORS_SOUND_MODE: 'mode',
        PICOLABSENSORS_SOUND_SUPERRISE: 'superrise',
        PICOLABSENSORS_SOUND_OHOH: 'ohoh',
        PICOLABSENSORS_SOUND_OHOH2: 'ohoh2',
        PICOLABSENSORS_SOUND_CUTE: 'cute',
        PICOLABSENSORS_SOUND_HAPPY: 'happy',
        PICOLABSENSORS_SOUND_SAD: 'sad',
        PICOLABSENSORS_SOUND_SAD2: 'sad2',
        PICOLABSENSORS_PS2READDATA: 'PS2 read data',
        PICOLABSENSORS_PS2GETBUTTON: 'PS2 %1 button is pressed?',
        PICOLABSENSORS_PS2_UP: 'up',
        PICOLABSENSORS_PS2_DOWN: 'down',
        PICOLABSENSORS_PS2_LEFT: 'left',
        PICOLABSENSORS_PS2_RIGHT: 'right',
        PICOLABSENSORS_PS2_TRIANGLE: 'triangle',
        PICOLABSENSORS_PS2_CIRCLE: 'circle',
        PICOLABSENSORS_PS2_CROSS: 'cross',
        PICOLABSENSORS_PS2_SQUARE: 'square',
        PICOLABSENSORS_PS2_SELECT: 'select',
        PICOLABSENSORS_PS2_START: 'start',
        PICOLABSENSORS_PS2GETJOYSTICK: 'PS2 get joystick %1',
        PICOLABSENSORS_RGBULTRASONICINIT: 'RGB ultrasonic init data pin %1 RGB pin %2',
        PICOLABSENSORS_RGBULTRASONICSETCOLORSTYLE: 'set rgb ultrasonic %1 LED color %2 style %3',
        PICOLABSENSORS_NONE: 'none',
        PICOLABSENSORS_BREATHING: 'breathing',
        PICOLABSENSORS_ROTATE: 'rotate',
        PICOLABSENSORS_FLASH: 'flash',
        PICOLABSENSORS_RGBULTRASONICREADDISTANCE: 'rgb ultrasonic read distance'
    });
    Object.assign(Blockly.ScratchMsgs.locales['zh-cn'], {
        IRON_KIT_CATEGORY: '工程车套件',
        PICOLABSENSORS_INIT: '初始化工程车套件',
        PICOLABSENSORS_SETSERVODEGREE: '设置舵机 %1 角度 %2',
        PICOLABSENSORS_SETMOTORSPEED: '设置电机 %1 方向 %2 速度 %3',
        PICOLABSENSORS_FORWARD: '正转',
        PICOLABSENSORS_BACKWARD: '倒转',
        PICOLABSENSORS_STOPMOTOR: '电机 %1 刹车',
        PICOLABSENSORS_SETRGBLEDCOLOR: '设置RGB LED %1 颜色为 %2',
        PICOLABSENSORS_ALL: '全部',
        PICOLABSENSORS_LEFT: '左边',
        PICOLABSENSORS_RIGHT: '右边',
        PICOLABSENSORS_SETBUZZER: '蜂鸣器播放 %1',
        PICOLABSENSORS_SOUND_CONNECT: '连接',
        PICOLABSENSORS_SOUND_DISCONNECT: '断开连接',
        PICOLABSENSORS_SOUND_BUTTON: '按键',
        PICOLABSENSORS_SOUND_MODE: '模式',
        PICOLABSENSORS_SOUND_SUPERRISE: '惊讶',
        PICOLABSENSORS_SOUND_OHOH: '哦哦',
        PICOLABSENSORS_SOUND_OHOH2: '哦哦2',
        PICOLABSENSORS_SOUND_CUTE: '可爱',
        PICOLABSENSORS_SOUND_HAPPY: '开心',
        PICOLABSENSORS_SOUND_SAD: '伤心',
        PICOLABSENSORS_SOUND_SAD2: '伤心2',
        PICOLABSENSORS_PS2READDATA: 'PS2读取数据',
        PICOLABSENSORS_PS2GETBUTTON: 'PS2 %1 按键被按下?',
        PICOLABSENSORS_PS2_UP: '上',
        PICOLABSENSORS_PS2_DOWN: '下',
        PICOLABSENSORS_PS2_LEFT: '左',
        PICOLABSENSORS_PS2_RIGHT: '右',
        PICOLABSENSORS_PS2_TRIANGLE: '三角',
        PICOLABSENSORS_PS2_CIRCLE: '圆',
        PICOLABSENSORS_PS2_CROSS: '叉号',
        PICOLABSENSORS_PS2_SQUARE: '方块',
        PICOLABSENSORS_PS2_SELECT: '选择',
        PICOLABSENSORS_PS2_START: '开始',
        PICOLABSENSORS_PS2GETJOYSTICK: 'PS2获取摇杆 %1',
        PICOLABSENSORS_RGBULTRASONICINIT: 'RGB超声波传感器初始化 数据引脚 %1 RGB引脚 %2',
        PICOLABSENSORS_RGBULTRASONICSETCOLORSTYLE: '设置RGB超声波传感器 %1 LED颜色 %2 样式 %3',
        PICOLABSENSORS_NONE: '无',
        PICOLABSENSORS_BREATHING: '呼吸',
        PICOLABSENSORS_ROTATE: '旋转',
        PICOLABSENSORS_FLASH: '闪烁',
        PICOLABSENSORS_RGBULTRASONICREADDISTANCE: 'RGB超声波传感器读取距离'
    });
    return Blockly;
}

exports = addMsg;
